[package]
name = "ftp_view"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
connection-form = { workspace = true }
ftp = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
one-core = { workspace = true }
rust-i18n = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
